### ISSUE TITLE
not working on OSX

### ISSUE THREAD

**Issue by smiller171** [dgomesbr/atom-cform#1]
Not sure if I'm doing something wrong or what, but I can't make this work at all on OSX

**Comment by dgomesbr** [comment]
@smiller171, I used the example package created by ATOM. Could you elaborate on what you tried? I also added updates for the original beaknit/cform repo, after the merge happens I'll update this plugin here as well.

**Comment by smiller171** [comment]
I tried typing start, I tried typing out ec2 and no autocompletions came up, I tried toggling from the plugin menu (hotkey wasn't working on mac)

**Comment by dgomesbr** [comment]
are you on a json file? or at least using the set-syntax package? https://atom.io/packages/set-syntax

**Comment by smiller171** [comment]
I tried with both .json and .cform, and Atom recognized the syntax as json. I am not using set-syntax currently. Is that plugin needed to make yours work?

**Comment by jtheuer** [comment]
FYI: Had similar issues, worked for me after restarting atom.

**Comment by smiller171** [comment]
@jtheuer Thanks! That did it. I could have sworn I already tried that.

**Comment by dgomesbr** [comment]
Sorry for being so afk, trying to cope with the new launchings and port the original cform to here and port the new functionalities to the plugin.
